import datetime
import os
import allure
import pytest
from selenium.webdriver.common.keys import Keys
from page_object.LoginPage import LoginPage
from common.readconfig import ini
from page.webpage import sleep
from common.readvalue import ElementValue
from common.readelement import Element
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import random
import string
from random import randint

flight = Element('flight_083')
flightvalue = ElementValue('flightvalue_083')
cad_account = ElementValue('cad_account')
@allure.feature("TC(ECE)-083 Local Operator Create and Officer Processing Schedule Change Application (Approve) for Charter Cargo application")
class TestTrafficRightsRulesApprove:
    @pytest.fixture(scope='function', autouse=True)
    def open_flight(self, drivers):
        login = LoginPage(drivers)
        login.get_url(ini.url)

    @allure.story("Create CharterFlightCargo by Local Operator")
    def test_083(self, drivers):
        login = LoginPage(drivers)
        logout_elements = drivers.find_elements_by_xpath("//i[contains(@class, 'el-icon-caret-bottom')]")
        if len(logout_elements) > 0:
            login.is_click(flight["Logout"])
            login.is_click(flight['Logout_Yes'])

        elements = drivers.find_elements_by_xpath("//button[contains(span,'Login ')]")
        if len(elements) > 0:
            login.input_user_name(cad_account['CpaOfficerLoginName'])
            login.input_user_password(cad_account['CpaOfficerPassword'])
            login.click_login_button()
        WebDriverWait(drivers, 25, 0.8).until(EC.presence_of_element_located((By.TAG_NAME, 'h2')))

        # 跳转到/ApplicationView/CharterFlight/CreateCharterFlightCargoe页面
        login.get_url(ini.url + "#/ApplicationView/CharterFlight/CreateCharterFlightCargo")
        drivers.implicitly_wait(30)

        login.input_text(flight['Registration_Mark'], flightvalue['Registration_Mark'])
        sleep(2)
        login.is_click(flight['Aircraft_Type'])
        sleep(2)
        login.input_text(flight['Aircraft_Type'], flightvalue['Aircraft_Type'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[1]/div/div[5]/div[1]/div/div/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.is_click(flight['Aircraft_Nationality'])
        sleep(2)
        login.input_text(flight['Aircraft_Nationality'], flightvalue['Aircraft_Nationality'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[1]/div/div[5]/div[2]/div/div/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['Name_of_Charterer'], flightvalue['Name_of_Charterer'])
        sleep(2)
        login.input_text(flight['Address_of_Charterer'], flightvalue['Address_of_Charterer'])
        sleep(2)
        login.is_click(flight['Local_Handling_Agent'])
        sleep(2)
        login.input_text(flight['Local_Handling_Agent'], flightvalue['Local_Handling_Agent'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[1]/div/div[8]/div/div/div[1]/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['Purpose_of_Service'], flightvalue['Purpose_of_Service'])
        sleep(2)
        login.input_text(flight['Points_of_landing_enRoute'], flightvalue['Points_of_landing_enRoute'])
        sleep(2)

        r = random.choice(string.ascii_letters)
        FlightNo1 = "CPA" + str(randint(1, 9999)) + r
        FlightNo2 = "CPA" + str(randint(1, 9999)) + r
        FlightNo3 = "CPA" + str(randint(1, 9999)) + r
        FlightNo4 = "CPA" + str(randint(1, 9999)) + r
        FlightNo5 = "CPA" + str(randint(1, 9999)) + r
        FlightNo6 = "CPA" + str(randint(1, 9999)) + r
        FlightNo7 = "CPA" + str(randint(1, 9999)) + r
        FlightNo8 = "CPA" + str(randint(1, 9999)) + r

        # FlightNo1
        login.is_click(flight['ServiceType_1'])
        sleep(2)
        login.input_text(flight['ServiceType_1'], flightvalue['ServiceType_1'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[1]/td[2]/div/span/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['FlightNo_1'], FlightNo1)
        sleep(2)
        login.input_text(flight['From_1'], flightvalue['From'])
        sleep(2)
        login.input_text(flight['To_1'], flightvalue['To'])
        sleep(2)
        login.is_click(flight['DOP_1_1'])
        sleep(2)
        login.is_click(flight['DOP_1_2'])
        sleep(2)
        login.is_click(flight['DOP_1_3'])
        sleep(2)
        login.is_click(flight['DOP_1_4'])
        sleep(2)
        login.is_click(flight['DOP_1_5'])
        sleep(2)
        login.is_click(flight['DOP_1_6'])
        sleep(2)
        login.is_click(flight['DOP_1_7'])
        sleep(2)
        login.input_text(flight['CargoAmount_1'], flightvalue['CargoAmount_1'])
        sleep(2)
        login.input_text(flight['PortFrom_1'], flightvalue['PortFrom_1'])
        sleep(2)
        login.input_text(flight['PortTo_1'], flightvalue['PortTo_1'])
        sleep(2)
        login.input_text(flight['LocalTime_STD_1'], flightvalue['LocalTime_STD_1'])
        sleep(2)
        login.input_text(flight['Consignor_1'], flightvalue['Consignor_1'])
        sleep(2)
        login.input_text(flight['Consignee_1'], flightvalue['Consignee_1'])
        sleep(2)
        login.input_text(flight['Description_1'], flightvalue['Description_1'])
        sleep(2)
        login.is_click(flight['Belly_1'])
        sleep(2)
        login.is_click(flight['Carriage_1'])
        sleep(2)
        login.input_text(flight['Remarks_1'], flightvalue['Remarks_1'])
        sleep(2)

        # FlightNo2
        login.is_click(flight['ServiceType_2'])
        sleep(2)
        login.input_text(flight['ServiceType_2'], flightvalue['ServiceType_1'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[2]/td[1]/div/span/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['FlightNo_2'], FlightNo2)
        sleep(2)
        login.is_click(flight['Diff_2'])
        sleep(2)
        login.input_text(flight['Diff_2'], flightvalue['Diff'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[2]/td[3]/div/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['CargoAmount_2'], flightvalue['CargoAmount_2'])
        sleep(2)
        login.input_text(flight['PortFrom_2'], flightvalue['PortFrom_2'])
        sleep(2)
        login.input_text(flight['PortTo_2'], flightvalue['PortTo_2'])
        sleep(2)
        login.input_text(flight['LocalTime_STA_2'], flightvalue['LocalTime_STA_2'])
        sleep(2)
        login.input_text(flight['Consignor_2'], flightvalue['Consignor_2'])
        sleep(2)
        login.input_text(flight['Consignee_2'], flightvalue['Consignee_2'])
        sleep(2)
        login.input_text(flight['Description_2'], flightvalue['Description_2'])
        sleep(2)
        login.is_click(flight['Carriage_2'])
        sleep(2)
        login.is_click(flight['PCCL_2'])
        sleep(2)
        login.input_text(flight['Remarks_2'], flightvalue['Remarks_2'])
        sleep(2)

        # FlightNo3
        login.is_click(flight['ServiceType_3'])
        sleep(2)
        login.input_text(flight['ServiceType_3'], flightvalue['ServiceType_1'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[3]/td[2]/div/span/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['FlightNo_3'], FlightNo3)
        sleep(2)
        login.input_text(flight['From_3'], flightvalue['From'])
        sleep(2)
        login.input_text(flight['To_3'], flightvalue['To'])
        sleep(2)
        login.is_click(flight['DOP_3_1'])
        sleep(2)
        login.is_click(flight['DOP_3_2'])
        sleep(2)
        login.is_click(flight['DOP_3_3'])
        sleep(2)
        login.is_click(flight['DOP_3_4'])
        sleep(2)
        login.is_click(flight['DOP_3_5'])
        sleep(2)
        login.is_click(flight['DOP_3_6'])
        sleep(2)
        login.is_click(flight['DOP_3_7'])
        sleep(2)
        login.input_text(flight['CargoAmount_3'], flightvalue['CargoAmount_3'])
        sleep(2)
        login.input_text(flight['PortFrom_3'], flightvalue['PortFrom_3'])
        sleep(2)
        login.input_text(flight['PortTo_3'], flightvalue['PortTo_3'])
        sleep(2)
        login.input_text(flight['LocalTime_STD_3'], flightvalue['LocalTime_STD_3'])
        sleep(2)
        login.input_text(flight['Consignor_3'], flightvalue['Consignor_3'])
        sleep(2)
        login.input_text(flight['Consignee_3'], flightvalue['Consignee_3'])
        sleep(2)
        login.input_text(flight['Description_3'], flightvalue['Description_3'])
        sleep(2)
        login.input_text(flight['Remarks_3'], flightvalue['Remarks_3'])
        sleep(2)

        # FlightNo4
        login.is_click(flight['ServiceType_4'])
        sleep(2)
        login.input_text(flight['ServiceType_4'], flightvalue['ServiceType_1'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[4]/td[1]/div/span/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['FlightNo_4'], FlightNo4)
        sleep(2)
        login.is_click(flight['Diff_4'])
        sleep(2)
        login.input_text(flight['Diff_4'], flightvalue['Diff'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[4]/td[3]/div/div/div[1]/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['CargoAmount_4'], flightvalue['CargoAmount_4'])
        sleep(2)
        login.input_text(flight['PortFrom_4'], flightvalue['PortFrom_4'])
        sleep(2)
        login.input_text(flight['PortTo_4'], flightvalue['PortTo_4'])
        sleep(2)
        login.input_text(flight['LocalTime_STA_4'], flightvalue['LocalTime_STA_4'])
        sleep(2)
        login.input_text(flight['Consignor_4'], flightvalue['Consignor_4'])
        sleep(2)
        login.input_text(flight['Consignee_4'], flightvalue['Consignee_4'])
        sleep(2)
        login.input_text(flight['Description_4'], flightvalue['Description_4'])
        sleep(2)
        login.input_text(flight['Remarks_4'], flightvalue['Remarks_4'])
        sleep(2)

        # FlightNo5
        login.is_click(flight['ServiceType_5'])
        sleep(2)
        login.input_text(flight['ServiceType_5'], flightvalue['ServiceType_1'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[5]/td[2]/div/span/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['FlightNo_5'], FlightNo5)
        sleep(2)
        login.input_text(flight['From_5'], flightvalue['From'])
        sleep(2)
        login.input_text(flight['To_5'], flightvalue['To'])
        sleep(2)
        login.is_click(flight['DOP_5_1'])
        sleep(2)
        login.is_click(flight['DOP_5_2'])
        sleep(2)
        login.is_click(flight['DOP_5_3'])
        sleep(2)
        login.is_click(flight['DOP_5_4'])
        sleep(2)
        login.is_click(flight['DOP_5_5'])
        sleep(2)
        login.is_click(flight['DOP_5_6'])
        sleep(2)
        login.is_click(flight['DOP_5_7'])
        sleep(2)
        login.input_text(flight['CargoAmount_5'], flightvalue['CargoAmount_5'])
        sleep(2)
        login.input_text(flight['PortFrom_5'], flightvalue['PortFrom_5'])
        sleep(2)
        login.input_text(flight['PortTo_5'], flightvalue['PortTo_5'])
        sleep(2)
        login.input_text(flight['LocalTime_STA_5'], flightvalue['LocalTime_STA_5'])
        sleep(2)
        login.input_text(flight['Consignor_5'], flightvalue['Consignor_5'])
        sleep(2)
        login.input_text(flight['Consignee_5'], flightvalue['Consignee_5'])
        sleep(2)
        login.input_text(flight['Description_5'], flightvalue['Description_5'])
        sleep(2)
        login.is_click(flight['Belly_5'])
        sleep(2)
        login.input_text(flight['Remarks_5'], flightvalue['Remarks_5'])
        sleep(2)

        # FlightNo6
        login.is_click(flight['ServiceType_6'])
        sleep(2)
        login.input_text(flight['ServiceType_6'], flightvalue['ServiceType_1'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[6]/td[1]/div/span/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['FlightNo_6'], FlightNo6)
        sleep(2)
        login.is_click(flight['Diff_6'])
        sleep(2)
        login.input_text(flight['Diff_6'], flightvalue['Diff'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[6]/td[3]/div/div/div[1]/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['CargoAmount_6'], flightvalue['CargoAmount_6'])
        sleep(2)
        login.input_text(flight['PortFrom_6'], flightvalue['PortFrom_6'])
        sleep(2)
        login.input_text(flight['PortTo_6'], flightvalue['PortTo_6'])
        sleep(2)
        login.input_text(flight['LocalTime_STD_6'], flightvalue['LocalTime_STD_6'])
        sleep(2)
        login.input_text(flight['Consignor_6'], flightvalue['Consignor_6'])
        sleep(2)
        login.input_text(flight['Consignee_6'], flightvalue['Consignee_6'])
        sleep(2)
        login.input_text(flight['Description_6'], flightvalue['Description_6'])
        sleep(2)
        login.is_click(flight['Belly_6'])
        sleep(2)
        login.input_text(flight['Remarks_6'], flightvalue['Remarks_6'])
        sleep(2)

        # FlightNo7
        login.is_click(flight['ServiceType_7'])
        sleep(2)
        login.input_text(flight['ServiceType_7'], flightvalue['ServiceType_2'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[7]/td[2]/div/span/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['FlightNo_7'], FlightNo7)
        sleep(2)
        login.input_text(flight['From_7'], flightvalue['From'])
        sleep(2)
        login.input_text(flight['To_7'], flightvalue['To'])
        sleep(2)
        login.is_click(flight['DOP_7_7'])
        sleep(2)
        login.is_click(flight['DOP_7_6'])
        sleep(2)
        login.is_click(flight['DOP_7_5'])
        sleep(2)
        login.is_click(flight['DOP_7_4'])
        sleep(2)
        login.is_click(flight['DOP_7_3'])
        sleep(2)
        login.is_click(flight['DOP_7_2'])
        sleep(2)
        login.is_click(flight['DOP_7_1'])
        sleep(2)
        login.input_text(flight['CargoAmount_7'], flightvalue['CargoAmount_7'])
        sleep(2)
        login.input_text(flight['PortFrom_7'], flightvalue['PortFrom_7'])
        sleep(2)
        login.input_text(flight['PortTo_7'], flightvalue['PortTo_7'])
        sleep(2)
        login.input_text(flight['LocalTime_STD_7'], flightvalue['LocalTime_STD_7'])
        sleep(2)
        login.input_text(flight['Consignor_7'], flightvalue['Consignor_7'])
        sleep(2)
        login.input_text(flight['Consignee_7'], flightvalue['Consignee_7'])
        sleep(2)
        login.input_text(flight['Description_7'], flightvalue['Description_7'])
        sleep(2)
        login.is_click(flight['Carriage_7'])
        sleep(2)
        login.input_text(flight['Remarks_7'], flightvalue['Remarks_7'])
        sleep(2)

        # FlightNo8
        login.is_click(flight['ServiceType_8'])
        sleep(2)
        login.input_text(flight['ServiceType_8'], flightvalue['ServiceType_2'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[8]/td[1]/div/span/div/div/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['FlightNo_8'], FlightNo8)
        sleep(2)
        login.is_click(flight['Diff_8'])
        sleep(2)
        login.input_text(flight['Diff_8'], flightvalue['Diff'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[3]/div/div[3]/table/tbody/tr[8]/td[3]/div/div/div[1]/input").send_keys(Keys.ENTER)
        sleep(2)
        login.input_text(flight['CargoAmount_8'], flightvalue['CargoAmount_8'])
        sleep(2)
        login.input_text(flight['PortFrom_8'], flightvalue['PortFrom_8'])
        sleep(2)
        login.input_text(flight['PortTo_8'], flightvalue['PortTo_8'])
        sleep(2)
        login.input_text(flight['LocalTime_STA_8'], flightvalue['LocalTime_STA_8'])
        sleep(2)
        login.input_text(flight['Consignor_8'], flightvalue['Consignor_8'])
        sleep(2)
        login.input_text(flight['Consignee_8'], flightvalue['Consignee_8'])
        sleep(2)
        login.input_text(flight['Description_8'], flightvalue['Description_8'])
        sleep(2)
        login.is_click(flight['Carriage_8'])
        sleep(2)
        login.input_text(flight['Remarks_8'], flightvalue['Remarks_8'])
        sleep(2)
        login.input_text(flight['Remark'], flightvalue['Remarks'])
        sleep(2)
        login.is_click(flight['Confirm'])
        sleep(2)
        login.is_click(flight['PreviewAndSubmit'])
        sleep(2)
        login.is_click(flight['Submit'])
        sleep(10)
        login.is_click(flight['Submit_ok'])
        sleep(2)

        date = (datetime.datetime.now() + datetime.timedelta(days=1)).strftime("%d/%m/%Y")
        login.is_click(flight['ClickCharterAllCargo'])
        sleep(2)
        login.input_text(flight['SubmittedTo'], date)
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[7]/div[1]/div/div/div[2]/input").send_keys(Keys.ENTER)
        sleep(2)
        login.is_click(flight['SearchMsg'])
        sleep(2)
        refNo = drivers.find_element_by_xpath("//*[@id='testRefNo00']").text

        current_path = os.path.abspath(__file__)
        filename = os.path.dirname(current_path) + '/TestData/Out/AppRefNo.txt'
        # 保存refNo
        with open(filename, 'w') as f:
            f.write(refNo)
        # 保存flightNo
        name_list = [FlightNo1, FlightNo2, FlightNo3, FlightNo4, FlightNo5, FlightNo6, FlightNo7, FlightNo8]
        filename2 = os.path.dirname(current_path) + '/TestData/Out/FlightNo.txt'
        with open(filename2, "w") as f:
            for i in name_list:
                f.writelines("{}\n".format(i))

        logout_elements = drivers.find_elements_by_xpath("//i[contains(@class, 'el-icon-caret-bottom')]")
        if len(logout_elements) > 0:
            login.is_click(flight["Logout"])
            login.is_click(flight['Logout_Yes'])

        elements = drivers.find_elements_by_xpath("//button[contains(span,'Login ')]")
        if len(elements) > 0:
            login.input_user_name(cad_account['OfficerLoginName'])
            login.input_user_password(cad_account['OfficerPassword'])
            login.click_login_button()
        WebDriverWait(drivers, 20, 0.8).until(EC.presence_of_element_located((By.TAG_NAME,'h2')))

        # 跳转到/View/Messages页面
        login.get_url(ini.url + "#/View/Messages")
        drivers.implicitly_wait(30)

        login.is_click(flight['AdvancedSearch'])
        sleep(2)
        login.input_text(flight['Sender'], cad_account['CpaOfficerLoginName'])
        sleep(2)
        login.input_text(flight['ReferenceNo'], refNo)
        sleep(2)
        login.is_click(flight['CharterAllCargo'])
        sleep(2)
        login.is_click(flight['Search_msg'])
        sleep(2)
        login.is_click(flight['msg'])
        sleep(2)
        login.is_click(flight['Approve'])
        try:
            login.is_click(flight['Proceed'])
            sleep(2)
        except:
            print("Proceed button not exist")
        sleep(2)
        login.is_click(flight['Send'])
        sleep(5)
        login.is_click(flight['Send_ok'])
        sleep(2)

        logout_elements = drivers.find_elements_by_xpath("//i[contains(@class, 'el-icon-caret-bottom')]")
        if len(logout_elements) > 0:
            login.is_click(flight["Logout"])
            login.is_click(flight['Logout_Yes'])


if __name__ == '__main__':
    pytest.main(['TestCase/test_tc_e2e_083_1.py'])