#!/usr/bin/env python3
# -*- coding:utf-8 -*-
import os

import pytest
import allure
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from common.readconfig import ini
from page_object.LoginPage import LoginPage
from page.webpage import sleep
from common.readelement import Element
from common.readvalue import ElementValue
from utils.logger import log

flight = Element('flight_082')
flightValue = ElementValue('flightValue_082')
accountValue = ElementValue('cad_account')

@allure.feature("[TC(E2E)-082] 02: Local Operator Create and Officer Processing Schedule Change Application (Approve) for Charter Pax application")
class TestScheduleChangeForCharterPax:
    @pytest.fixture(scope='function', autouse=True)
    def open_flight(self, drivers):
        """打开登录页面"""
        login = LoginPage(drivers)
        login.get_url(ini.url)

    @allure.story("Schedule Change Application (Approve) for Charter Pax application")
    def test_e2e_0822(self, drivers):
        login = LoginPage(drivers)
        logout_elements = drivers.find_elements_by_xpath("//i[contains(@class, 'el-icon-caret-bottom')]")
        if len(logout_elements) > 0:
            login.is_click(flight["Logout"])
            login.is_click(flight["Logout_Yes"])
        elements = drivers.find_elements_by_xpath("//button[contains(span,'Login ')]")
        if len(elements) > 0:
            login.input_user_name(accountValue['CpaOfficerLoginName'])
            login.input_user_password(accountValue['CpaOfficerPassword'])
            login.click_login_button()
        WebDriverWait(drivers, 15, 0.8).until(EC.presence_of_element_located((By.TAG_NAME, 'h2')))

        # 跳转到Create Schedule Change Application页面
        login.get_url(ini.url + "#/ApplicationView/ScheduleChange/FlightSchedule")
        drivers.implicitly_wait(30)
        sleep(5)
        assert drivers.find_element_by_css_selector("h2").text == "Create Schedule Change Application"

        # 读取fightNo
        current_path = os.path.abspath(__file__)
        filename = os.path.dirname(current_path)+'/TestFile/FlightNo.txt'
        with open(filename, 'r') as f:
            for num, line in enumerate(f):
                if num == 0:
                    flightNo1 = line.rstrip()
                    log.info("-------------------------flightNo1: " + flightNo1)
                if num == 1:
                    flightNo3 = line.rstrip()
                    log.info("-------------------------flightNo3: " + flightNo3)
                if num == 2:
                    flightNo5 = line.rstrip()
                    log.info("-------------------------flightNo5: " + flightNo5)
                if num == 3:
                    flightNo6 = line.rstrip()
                    log.info("-------------------------flightNo6: " + flightNo6)
                if num == 4:
                    flightNo7 = line.rstrip()
                    log.info("-------------------------flightNo7: " + flightNo7)
        login.input_text(flight['Operation_Period_From'], flightValue['Operation_Period_From'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[4]/div/div/div/div[1]/input").send_keys(Keys.ENTER)
        login.input_text(flight['Operation_Period_To'], flightValue['Operation_Period_To'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[4]/div/div/div/div[2]/input").send_keys(Keys.ENTER)
        login.is_click(flight['Charter_Passenger2'])
        login.is_click(flight['Flight_By_Period'])
        # Revise1
        login.input_text(flight['Flight_No'], flightNo1)
        login.is_click(flight['Search2'])
        sleep(2)
        login.is_click(flight['result_select'])
        sleep(2)
        login.is_click(flight['Revise'])
        sleep(2)
        login.is_click(flight['ChangeDop1_1'])
        login.is_click(flight['ChangeDop1_3'])
        login.is_click(flight['ChangeDop1_5'])
        login.is_click(flight['ChangeDop1_7'])
        login.input_text(flight['STD'], flightValue['Local_Time7'])
        login.input_text(flight['Remarks2'], flightValue['Remarks2'] + "1")
        login.input_text(flight['STA'], flightValue['Local_Time8'])
        login.input_text(flight['Remarks3'], flightValue['Remarks2'] + "2")
        sleep(2)
        login.is_click(flight['Save'])
        sleep(2)
        # Revise2
        login.input_text(flight['Flight_No'], flightNo3)
        login.is_click(flight['Search2'])
        sleep(2)
        login.is_click(flight['result_select'])
        sleep(2)
        login.is_click(flight['Revise'])
        sleep(2)
        login.input_text(flight['From_9'], flightValue['Operation_Period_From2'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[1]/td[6]/div/span/div/input").send_keys(Keys.ENTER)
        login.input_text(flight['To_9'], flightValue['Operation_Period_To2'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[1]/td[7]/div/span/div/input").send_keys(Keys.ENTER)
        login.input_text(flight['STD'], flightValue['Local_Time9'])
        login.input_text(flight['Remarks2'], flightValue['Remarks2'] + "3")
        login.input_text(flight['STA'], flightValue['Local_Time5'])
        login.input_text(flight['Remarks3'], flightValue['Remarks2'] + "4")
        sleep(2)
        login.is_click(flight['Save'])
        sleep(2)
        # Revise3
        login.input_text(flight['Flight_No'], flightNo5)
        login.is_click(flight['Search2'])
        sleep(2)
        login.is_click(flight['result_select'])
        sleep(2)
        login.is_click(flight['Revise'])
        sleep(2)
        login.input_text(flight['From_9'], flightValue['Operation_Period_From'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[1]/td[6]/div/span/div/input").send_keys(Keys.ENTER)
        login.input_text(flight['To_9'], flightValue['Operation_Period_From2'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[1]/td[7]/div/span/div/input").send_keys(Keys.ENTER)
        login.input_text(flight['STA2'], flightValue['Local_Time1'])
        login.input_text(flight['Remarks2'], flightValue['Remarks2'] + "5")
        login.is_click(flight['Change_In_Out_Diff1'])
        login.input_text(flight['Change_In_Out_Diff1'], flightValue['In_Out_Diff'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[2]/td[4]/div/span/div/div/div[1]/input").send_keys(Keys.ENTER)
        login.input_text(flight['STD2'], flightValue['Local_Time3'])
        login.input_text(flight['Remarks3'], flightValue['Remarks2'] + "6")
        sleep(2)
        # add
        login.is_click(flight['Add'])
        sleep(1)
        login.input_text(flight['FlightNo_9'], flightNo5)
        login.input_text(flight['From_10'], flightValue['Operation_Period_From3'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[3]/td[6]/div/span/div/input").send_keys(Keys.ENTER)
        login.input_text(flight['To_10'], flightValue['Operation_Period_To'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[3]/td[7]/div/span/div/input").send_keys(Keys.ENTER)
        login.is_click(flight['AddDop1_1'])
        login.is_click(flight['AddDop1_2'])
        login.is_click(flight['AddDop1_3'])
        login.is_click(flight['AddDop1_4'])
        login.is_click(flight['AddDop1_5'])
        login.is_click(flight['AddDop1_6'])
        login.is_click(flight['AddDop1_7'])
        login.is_click(flight['Aircraft_Type'])
        login.input_text(flight['Aircraft_Type'], flightValue['Aircraft_Type'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[3]/td[15]/div/span/div/div[1]/input").send_keys(Keys.ENTER)
        login.input_text(flight['No_of_Pax_9'], flightValue['No_of_Pax3'])
        login.input_text(flight['Route1'], flightValue['Route1'])
        login.is_click(flight['STA3'])
        login.input_text(flight['STA3'], flightValue['Local_Time1'])
        login.input_text(flight['Remarks4'], flightValue['Remarks2'] + "5")
        sleep(1)
        login.input_text(flight['FlightNo_10'], flightNo6)
        login.is_click(flight['Change_In_Out_Diff2'])
        login.input_text(flight['Change_In_Out_Diff2'], flightValue['In_Out_Diff'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[4]/td[4]/div/span/div/div/div[1]/input").send_keys(Keys.ENTER)
        login.is_click(flight['Aircraft_Type2'])
        login.input_text(flight['Aircraft_Type2'], flightValue['Aircraft_Type'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[4]/td[14]/div/span/div/div/input").send_keys(Keys.ENTER)
        login.input_text(flight['No_of_Pax_10'], flightValue['No_of_Pax1'])
        login.input_text(flight['Route2'], flightValue['Route2'])
        login.is_click(flight['STD3'])
        login.input_text(flight['STD3'], flightValue['Local_Time3'])
        login.input_text(flight['Remarks5'], flightValue['Remarks2'] + "6")
        sleep(2)
        login.is_click(flight['Save'])
        sleep(2)
        # Revise4
        login.input_text(flight['Flight_No'], flightNo7)
        login.input_text(flight['Operation_Period_To'], flightValue['Operation_Period_From'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[4]/div/div/div/div[2]/input").send_keys(Keys.ENTER)
        login.is_click(flight['Flight_by_Day'])
        login.is_click(flight['Search2'])
        sleep(60)
        login.is_click(flight['result_select'])
        sleep(2)
        login.is_click(flight['Revise'])
        sleep(2)
        login.is_click(flight['Aircraft_Type3'])
        login.input_text(flight['Aircraft_Type3'], flightValue['Aircraft_Type2'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[1]/td[15]/div/span/div/div/input").send_keys(Keys.ENTER)
        login.input_text(flight['Remarks2'], flightValue['Remarks2'] + "7")
        login.is_click(flight['Aircraft_Type4'])
        login.input_text(flight['Aircraft_Type4'], flightValue['Aircraft_Type2'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[19]/div[1]/div/div[2]/div[2]/div[3]/table/tbody/tr[2]/td[14]/div/span/div/div[1]/input").send_keys(Keys.ENTER)
        login.input_text(flight['Remarks3'], flightValue['Remarks2'] + "8")
        sleep(2)
        login.is_click(flight['Save'])
        sleep(60)

        login.input_text(flight['Remarks6'], flightValue['Remarks'])
        # Upload file
        login.is_click(flight['Upload_Related_Documents2'])
        sleep(2)
        login.is_click(flight['Doc_Type_Input'])
        login.input_text(flight['Doc_Type_Input'], flightValue['Document_Type_Others'])
        sleep(2)
        drivers.find_element_by_xpath("//*[@id='testNewDocumentUpload']").send_keys(Keys.ENTER)
        sleep(2)
        current_path = os.path.abspath(__file__)
        file_path = os.path.dirname(current_path) + "/TestFile/other_supports.pdf"
        drivers.find_element_by_xpath("//input[@type ='file']").send_keys(file_path)
        sleep(3)
        login.is_click(flight['Indefinite'])
        sleep(3)
        login.is_click(flight['UploadButton'])
        sleep(3)

        login.is_click(flight['Click_Condition2'])
        sleep(2)
        login.is_click(flight['Save_AS_Draft'])
        sleep(10)
        login.is_click(flight['Preview_And_Submit2'])
        sleep(10)
        login.is_click(flight['Click_Submit2'])
        sleep(10)
        login.is_click(flight['Submit_OK2'])
        sleep(6)

        # 从CPATEST03用户到 Officer1用户切换
        login.is_click(flight["Logout"])
        login.is_click(flight["Logout_Yes"])
        login.input_user_name(accountValue['OfficerLoginName'])
        login.input_user_password(accountValue['OfficerPassword'])
        login.click_login_button()
        sleep(15)

        login.get_url(ini.url + "#/View/Messages")
        sleep(5)
        login.is_click(flight['Advanced_Search'])
        sleep(1)
        login.input_text(flight['Sender'], accountValue['CpaOfficerLoginName'])
        sleep(1)
        login.is_click(flight['Schedule_Change'])
        sleep(1)
        login.is_click(flight['Search'])
        sleep(6)
        login.is_click(flight['Reference_No'])
        sleep(6)
        login.is_click(flight['Flight_Select'])
        sleep(2)
        login.is_click(flight['Modify_Button'])
        sleep(2)
        login.is_click(flight['ModifyDop1_2'])
        sleep(2)
        login.is_click(flight['ModifyDop1_3'])
        sleep(2)
        login.is_click(flight['ModifyDop1_4'])
        sleep(2)
        login.is_click(flight['ModifyDop1_6'])
        sleep(2)
        login.input_text(flight['No_of_Pax_11'], flightValue['No_of_Pax3'])
        sleep(2)
        login.is_click(flight['STD4'])
        sleep(2)
        login.input_text(flight['STD4'], flightValue['Local_Time10'])
        sleep(2)
        login.input_text(flight['No_of_Pax_12'], flightValue['No_of_Pax5'])
        sleep(2)
        login.is_click(flight['STA4'])
        sleep(2)
        login.input_text(flight['STA4'], flightValue['Local_Time11'])
        sleep(2)
        login.is_click(flight['Save1'])
        sleep(5)

        login.is_click(flight['Upload_Button'])
        sleep(2)
        login.is_click(flight['Lease_Aircraft_Button'])
        sleep(2)
        login.is_click(flight['Upload_Document_Lessor_Operator_Input'])
        login.input_text(flight['Upload_Document_Lessor_Operator_Input'], flightValue['Lessor_Operator_ICAO'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[13]/div[1]/div/div[2]/form/div[6]/div[1]/div/div/div/div[1]/input").send_keys(Keys.ENTER)
        login.is_click(flight['Upload_Document_Type_Input'])
        login.input_text(flight['Upload_Document_Type_Input'], flightValue['Document_Type'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[13]/div[1]/div/div[2]/form/div[7]/div/div/div/div/div/div[1]/input").send_keys(Keys.ENTER)
        login.input_text(flight['Upload_Document_Registration_Mark'], flightValue['Registration_Mark2'])
        login.is_click(flight['Upload_Document_Aircraft_Type_Input'])
        login.input_text(flight['Upload_Document_Aircraft_Type_Input'], flightValue['Aircraft_Type3'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[13]/div[1]/div/div[2]/form/div[8]/div[2]/div/div/div/div[1]/input").send_keys(Keys.ENTER)
        login.input_text(flight['Upload_Document_Expiry_Date_Input'], flightValue['Expiry_Date'])
        drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/div[13]/div[1]/div/div[2]/form/div[9]/div/div/div/div/input").send_keys(Keys.ENTER)
        login.input_text(flight['Upload_Document_Enclosure'], flightValue['Enclosure_Reference'])
        login.input_text(flight['Upload_Document_Remarks'], flightValue['Remarks3'])
        login.is_click(flight['Upload_Click'])
        sleep(2)
        login.is_click(flight['Upload_Click_OK'])
        sleep(2)
        login.is_click(flight['Select_From_Document_Library_Button'])
        sleep(2)
        login.is_click(flight['Select_From_Document_Library_Select_Record'])
        sleep(2)
        login.is_click(flight['Select_From_Document_Library_Confirm'])
        sleep(2)

        login.is_click(flight['Upload_Application_related_Document_Button'])
        sleep(2)
        login.is_click(flight['New_Doc_Type_Input'])
        login.input_text(flight['New_Doc_Type_Input'], flightValue['Document_Type_Others'])
        sleep(1)
        drivers.find_element_by_xpath("//*[@id='testNewDocumentUpload']").send_keys(Keys.ENTER)
        sleep(1)
        current_path = os.path.abspath(__file__)
        file_path = os.path.dirname(current_path) + "/TestFile/other_supports.pdf"
        drivers.find_element_by_xpath("/html/body/div[7]/div/div[2]/form/div[1]/div/div/div/span/div[2]/div/div/input").send_keys(file_path)
        sleep(2)
        login.is_click(flight['New_Indefinite'])
        sleep(2)
        login.is_click(flight['Upload_Application_related_Document_Upload'])
        sleep(2)
        login.is_click(flight['View_Uploaded_Documents'])
        sleep(2)
        login.is_click(flight['View_Uploaded_Documents_Close'])
        sleep(2)
        # login.input_text(flight['Remarks_input'], flightValue['Remarks4'])
        login.is_click(flight['CAD_Remarks'])
        sleep(2)
        login.input_text(flight['CAD_Remarks_Text'], flightValue['CAD_Remarks'])
        sleep(1)

        login.is_click(flight['Approve1'])
        sleep(8)
        login.is_click(flight['Generate'])
        sleep(20)
        login.is_click(flight['Generate_And_Edit'])
        sleep(10)
        login.input_text(flight['Template_Office_Phone_No'], flightValue['Office_Phone_No'])
        login.input_text(flight['Template_Fax_No'], flightValue['Office_Fax_No'])
        login.input_text(flight['Template_Post'], flightValue['Post'])
        login.input_text(flight['Template_Company_Name'], flightValue['Company_Name'])
        login.input_text(flight['Template_Address1'], flightValue['Address1'])
        login.input_text(flight['Template_Address2'], flightValue['Address2'])
        login.input_text(flight['Template_Address3'], flightValue['Address3'])
        login.input_text(flight['Template_Signed_Area'], flightValue['Signed_Area'])
        sleep(1)
        login.is_click(flight['Template_RefreshPreview'])
        sleep(1)
        login.is_click(flight['Template_Download_As_Word'])
        sleep(1)
        login.is_click(flight['Template_Generate_PDF'])
        sleep(15)
        login.is_click(flight['Send'])
        sleep(10)
        login.is_click(flight['Send_OK'])
        sleep(3)

        # 从 Officer1 用户到 CPATEST03 用户切换
        login.is_click(flight["Logout"])
        login.is_click(flight["Logout_Yes"])
        login.input_user_name(accountValue['CpaOfficerLoginName'])
        login.input_user_password(accountValue['CpaOfficerPassword'])
        login.click_login_button()
        sleep(15)

        login.get_url(ini.url + "#/View/Messages")
        sleep(3)
        login.is_click(flight['CPA_Advanced_Search'])
        sleep(1)
        login.input_text(flight['CPA_Advanced_Sender'], accountValue['OfficerLoginName'])
        sleep(1)
        login.is_click(flight['CPA_Schedule_Change'])
        sleep(1)
        login.is_click(flight['CPA_Search'])
        sleep(2)
        login.is_click(flight['Reference_No2'])
        sleep(6)
        # login.get_url(ini.url + "#/View/FlightSchedule")
        # sleep(3)
        # login.is_click(flight['Aircraft_Category_Fixed'])
        # sleep(1)
        # login.input_text(flight['EffectiveOperation_Period_From'], flightValue['Operation_Period_From'])
        # drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[5]/div/div/div/div[1]/input").send_keys(Keys.ENTER)
        # sleep(1)
        # login.input_text(flight['EffectiveOperation_Period_To'], flightValue['Operation_Period_To'])
        # drivers.find_element_by_xpath("//*[@id='app']/div/div/section/div/form/div[5]/div/div/div/div[2]/input").send_keys(Keys.ENTER)
        # sleep(1)
        # login.is_click(flight["SFS_Service_Type_Charter_Pax"])
        # sleep(1)
        # login.is_click(flight["SFS_Service_Type_Ferry"])
        # sleep(1)
        # login.is_click(flight["SFS_Search"])
        # sleep(30)
        # login.is_click(flight["Total_Pages"])
        # sleep(10)

        login.is_click(flight["Logout"])
        login.is_click(flight["Logout_Yes"])

if __name__ == '__main__':
    pytest.main(['TestCase/TC_E2E_082/test_e2e_0822.py'])
